"""empty message

Revision ID: 173cf824a8fe
Revises: 9440a83122d4
Create Date: 2017-11-15 15:40:46.630552

"""

# revision identifiers, used by Alembic.
revision = '173cf824a8fe'
down_revision = '9440a83122d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('windowsLeft', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_giverId'), 'scores', ['giverId'], unique=False)
    op.create_index(op.f('ix_scores_quizId'), 'scores', ['quizId'], unique=False)
    op.drop_index('ix_scores_giverId', table_name='scores')
    op.drop_index('ix_scores_quizId', table_name='scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scores_quizId', 'scores', ['quizId'], unique=False)
    op.create_index('ix_scores_giverId', 'scores', ['giverId'], unique=False)
    op.drop_index(op.f('ix_scores_quizId'), table_name='scores')
    op.drop_index(op.f('ix_scores_giverId'), table_name='scores')
    op.drop_table('files')
    # ### end Alembic commands ###
