"""empty message

Revision ID: 70fb607c4403
Revises: b7aebde2fbdf
Create Date: 2017-11-07 19:24:01.831231

"""

# revision identifiers, used by Alembic.
revision = '70fb607c4403'
down_revision = 'b7aebde2fbdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizName', sa.String(length=128), nullable=True),
    sa.Column('creatorId', sa.Integer(), nullable=True),
    sa.Column('questionsIdList', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('questionName', sa.String(length=512), nullable=True),
    sa.Column('opt1', sa.String(length=128), nullable=True),
    sa.Column('opt2', sa.String(length=128), nullable=True),
    sa.Column('opt3', sa.String(length=128), nullable=True),
    sa.Column('opt4', sa.String(length=128), nullable=True),
    sa.Column('correctAns', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
