"""empty message

Revision ID: 9440a83122d4
Revises: 70fb607c4403
Create Date: 2017-11-07 21:24:25.109949

"""

# revision identifiers, used by Alembic.
revision = '9440a83122d4'
down_revision = '70fb607c4403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giverId', sa.Integer(), nullable=True),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answers', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['giverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quizId'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_giverId'), 'scores', ['giverId'], unique=False)
    op.create_index(op.f('ix_scores_quizId'), 'scores', ['quizId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_quizId'), table_name='scores')
    op.drop_index(op.f('ix_scores_giverId'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
